electron-vite/electron-vite-vue

package.json, src/render/components/HelloWorld.vue, vite.config.ts
**更新antdv样式按需加载 && 新增modifyVars 注释方便使用者自定义antd主题样式定义**
=> update: load ant-design-vue styles on demand

src/main/index.ts
Remove app.disableHardwareAcceleration() in main process
=> fix(main): remove disableHardwareAcceleration

README.md
=> Typo: Fixed typo in the README.md file

.github/workflows/release.yml, Dockerfile
目前暂时还不支持测试集成，后续调研下 e2e 测试和 vitest 单元测试集成一下
=> feat(ci): add github action :hammer:

README.md
=> Chore: i18n

package-lock.json, package.json, playwright.config.ts, test/example.spec.ts
=> feat(test): add playwright e2e test tool

packages/renderer/vite.config.ts
=> 默认build target版本编译时无法支持顶格await

README.md, README.zh-CN.md, package-lock.json, package.json, packages/main/index.ts, packages/preload/index.ts, packages/renderer/src/global.d.ts, packages/renderer/src/main.ts, packages/renderer/src/mainModules/builtinModuleSample.ts, packages/renderer/src/mainModules/ipcRendererSample.ts, packages/renderer/src/mainModules/nodeModulesSample.ts, packages/renderer/vite.config.ts
当前的模版默认使用 preload 注入。
None.
将 nodeIntegration 设置为默认项，并更新了文档。
将不含有 nodeIntegration 的模版设置为了 [withoutNodeIntegration](https://github.com/caoxiemeihao/electron-vue-vite/tree/withoutNodeIntegration) 分支，带有 nodeIntegration 的模版设置为 [nodeIntegration](https://github.com/caoxiemeihao/electron-vue-vite/tree/nodeIntegration) 分支。
=> feat(nodeIntegration): set nodeIntegration as true by default

packages/main/index.ts
=> chore: reomve useless code

packages/renderer/src/samples/node-api.ts
=> feat: use fs/promise instead fs

packages/main/vite.config.ts
=> chore: warning suppression

.vscode/extensions.json
=> chore: update vscode recommendations

packages/preload/loading.ts
=> fix: removeChild #121

scripts/watch.mjs
1. rebuild main and preload script will clear console log and display log on the next screen.
2. exit the command when closing the application.
=> Adjust the watch script

scripts/watch.mjs
In main and preload process console log Chinese characters will garbled.
fix the error.
=> fix: print Chinese characters are garbled in Windows terminal

packages/renderer/vite.config.ts
=> feat: sqlite3, serialport use-cases

packages/main/index.ts
new window example
Example: \#111
=> new window example

package.json
=> Modify a small alert( description is missed) when building.

README.md
=> Fix README.md Error

vite.config.ts
config server option by package.json
=> feat: config server option by package.json

electron/main/index.ts, package.json
=> fix(build): 处理构建报错&构建后的图片资源URL解析错误

package.json
electron                   ^19.0.3  →  ^19.0.8     
electron-builder      ^23.0.3  →  ^23.1.0     
typescript             ^4.7.3  →   ^4.7.4     
vite-plugin-electron   ^0.6.2  →   ^0.7.2     
vue                   ^3.2.36  →  ^3.2.37     
vue-tsc               ^0.36.0  →  ^0.38.3
=> chore: bump deps

.github/PULL_REQUEST_TEMPLATE.md
Update `PULL_REQUEST_TEMPLATE.md` template
=> chore: update `.github/PULL_REQUEST_TEMPLATE.md`

package.json
bump vite-plugin-electron to v0.7.5
=> chore: bump vite-plugin-electron to v0.7.5

README.md, package.json
About this PR.
1. Explains something about the Renderer process using C/C++ native modules, Node.js ESM packages, etc.
2. How to remove Renderer integraiton Node.js config.
3. Bump `vite-plugin-electron` to `v0.8.0`. *This might be a nice improvement*.
4. Issues https://github.com/electron-vite/electron-vite-vue/issues/169
=> Keep love 220720

.vscode/.debug.script.mjs, .vscode/launch.json, .vscode/tasks.json, vite.config.ts
[fix(🐞): correct bootstrap](https://github.com/electron-vite/electron-vite-vue/commit/d22104ed1233c834dfdc26ef5295eec9f2bbab68)
[feat(🌱): support Debug in VSCode](https://github.com/electron-vite/electron-vite-vue/commit/a7456a196385bfeb3504f6501a6ccc08b5be485d)
https://github.com/electron-vite/electron-vite-vue/issues/161
=> support Debug in VSCode  https://github.com/electron-vite/electron-vite-vue/issues/161

vite.config.ts
代码中存在一段 feat(🌱): support Debug in VSCode 字符串导致代码运行时报错
=> chore: 删除一段导致代码无法运行的文本

README.md, electron/electron-env.d.ts, package.json
=> Keep love 220721

.vscode/.debug.script.mjs, vite.config.ts
This PR for improvement Debug logic, easier to maintain. 🔧
=> refactor: better Debug logic

.vscode/tasks.json
Ref: electron-vite/electron-vite-boilerplate#27
Fix VS Code useless popup.
=> fix: update `problemMatcher`

vite.config.ts
=> fix: types warn

electron/main/index.ts
Comment out code to allow electron security warnings.
=> fix: allows electron security warnings, see #199

.github/workflows/release.yml
update GitHub action to build packages for different platforms.
See test in : https://github.com/yi-Xu-0100/electron-vite-vue/actions/runs/2736227031
=> ci: fix github action

.github/workflows/build.yml, README.md
- Add build badge for readme.
- Change release to build, because the CI is used to test package application.
- Update build trigger.
=> ci: release -> build

.github/workflows/build.yml, .github/workflows/ci.yml
Add CI to check not allowed files and lint.
ref: https://github.com/electron-vite/electron-vite-vue/pull/215#issuecomment-1194887032
See test in 
- PR: https://github.com/yi-Xu-0100/electron-vite-vue/pull/1
- Action: https://github.com/yi-Xu-0100/electron-vite-vue/actions/runs/2779851006
=> ci: add check action

package.json
=> Upgrade vite to 3.0.3，@vitejs/plugin-vue to 3.0.1

.vscode/launch.json
Cannot connect to the target at localhost:9229
=> Cannot connect to the target at localhost:9229 

.github/workflows/ci.yml
fix the new PR always trigger the CI(Check Not Allowed File Changes) test.
See new test in
- (non-trigger) https://github.com/yi-Xu-0100/electron-vite-vue/pull/2
- (trigger) https://github.com/yi-Xu-0100/electron-vite-vue/pull/3
=> ci: fix trigger condition

vite.config.ts
=> fix(Vite@.3x): Invalid URL #212

.vscode/settings.json
use json schema autocomplete `electron-builder.json5`,like this:
=> chore: update vscode json schema

package.json, vite.config.ts
- [chore:upd vite-plugin-electron to 0.9.1](https://github.com/electron-vite/electron-vite-vue/commit/f53dba80a3606927180771ff834738c26b7db93d)
- [refactor: better Debug config](https://github.com/electron-vite/electron-vite-vue/commit/642403f47827b8ca426f31054e5dc09f472a4acc)
=> refactor: better Debug config

package.json
=> chore: bump vite-electron-plugin to 0.4.6

package.json
=> :arrow_up: vite 升级到 4.0.0

LICENSE, package.json, src/style.css
Update all package and pull changes from the upstream (create-vite)
=> feat: pull code from upstream + update dependencies

electron/main/index.ts
=> fix: links open in app, not browser

electron/preload/index.ts
resolve `ipcRenderer`  methods all no returns that unable to receive returned information
=> fix: resolve ipcRenderer  no returns
